### ISSUE TITLE
Crashing 1.7.10

### ISSUE THREAD

**Issue by Felicitas12** [LakMoore/Smooth-Entity-Light#21]
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 256
	at lakmoore.sel.world.WorldSEL.func_72802_i(WorldSEL.java:49)
	at net.minecraft.client.multiplayer.WorldClient.func_72802_i(WorldClient.java:515)
	at ChunkCacheOF.getLightBrightnessForSkyBlocksRaw(ChunkCacheOF.java:71)
	at ChunkCacheOF.func_72802_i(ChunkCacheOF.java:61)
	at net.minecraft.block.Block.func_149677_c(Block.java:528)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:5032)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4784)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:327)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:325)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2382)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1657)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1392)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by Felicitas12** [comment]
maybe add try catch after: float lightPlayer = lc.lights[x & 15][y][z & 15];
